# Generated by Django 5.1.5 on 2025-04-22 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gtwt_app", "0003_announcement"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Announcement",
        ),
    ]
