# Generated by Django 5.1.5 on 2025-04-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gtwt_app", "0005_savedroute"),
    ]

    operations = [
        migrations.AddField(
            model_name="constructionzone",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
