# Generated by Django 5.1.5 on 2025-04-24 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtwt_app', '0007_constructionzone_color'),
    ]

    operations = [
    ]
