# Generated by Django 5.2 on 2025-04-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtwt_app', '0009_constructionzone_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedroute',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
