# Generated by Django 5.1.5 on 2025-04-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gtwt_app", "0010_savedroute_is_favorite"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
